image: docker:20
services:
  - docker:20-dind

stages:
  - build
  - release

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t gateway-semantic ./api
  only:
    - main
    - develop
    - /^release-.*$/

release:
  image: node:13
  stage: release
  before_script:
    - docker build -t gateway-semantic ./api
  only:
    refs:
    - main
    - develop
    - rc
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  script:
    - cd ./api
    - npm install @semantic-release/gitlab @semantic-release/changelog @eclass/semantic-release-docker
    - npx semantic-release
